"use client";

import { useState } from "react";
import type { CrmAppointment, CrmClient, CrmContact, CrmLead, CrmTask, CrmTeamMember } from "../../db/crm";
import { Badge, dateTime, EmptyState, money, shortDate } from "./ui";

type Mutate = (input: Record<string, unknown>, success: string) => Promise<void>;

export function ContactsView({ contacts, clients, onAddContact }: { contacts: CrmContact[]; clients: CrmClient[]; onAddContact: () => void }) {
  const [query, setQuery] = useState("");
  const filtered = contacts.filter((contact) => `${contact.firstName} ${contact.lastName} ${contact.phone ?? ""} ${contact.email ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const clientName = (id: string) => clients.find((client) => client.id === id)?.businessName ?? "Unknown client";
  return <div className="crm-view"><section className="crm-page-heading"><div><p>CONTACT DATABASE</p><h2>Contacts</h2><span>One customer record can connect to multiple leads, tasks, and appointments.</span></div><button className="crm-button-primary" onClick={onAddContact}>+ Add Contact</button></section><section className="crm-filterbar"><label className="crm-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search contacts" aria-label="Search contacts" /></label><span>{filtered.length} contacts</span></section>{filtered.length ? <section className="crm-contact-grid">{filtered.map((contact) => <article key={contact.id}><header><span className="crm-avatar">{contact.firstName[0]}{contact.lastName[0]}</span><div><strong>{contact.firstName} {contact.lastName}</strong><small>{clientName(contact.clientId)}</small></div><Badge tone={contact.marketingConsent === "granted" ? "green" : contact.marketingConsent === "revoked" ? "red" : "neutral"}>{contact.marketingConsent}</Badge></header><dl><div><dt>Phone</dt><dd>{contact.phone ?? "Not provided"}</dd></div><div><dt>Email</dt><dd>{contact.email ?? "Not provided"}</dd></div><div><dt>Last interaction</dt><dd>{shortDate(contact.lastInteractionAt)}</dd></div><div><dt>Lifetime value</dt><dd>{money(contact.lifetimeValueCents)}</dd></div></dl><footer>{contact.tags.map((tag) => <Badge key={tag} tone="purple">{tag}</Badge>)}</footer></article>)}</section> : <EmptyState title="No contacts yet" description="Add a contact or create a lead to build the customer database." action={<button className="crm-button-primary" onClick={onAddContact}>Add Contact</button>} />}</div>;
}

export function TasksView({ tasks, clients, mutate, onAddTask }: { tasks: CrmTask[]; clients: CrmClient[]; mutate: Mutate; onAddTask: () => void }) {
  const [filter, setFilter] = useState("OPEN");
  const visible = tasks.filter((task) => filter === "ALL" || (filter === "OPEN" ? !["COMPLETED", "CANCELED"].includes(task.status) : task.status === filter));
  return <div className="crm-view"><section className="crm-page-heading"><div><p>FOLLOW-UP WORK</p><h2>Tasks</h2><span>Keep every callback, estimate follow-up, and reminder accountable.</span></div><button className="crm-button-primary" onClick={onAddTask}>+ New Task</button></section><section className="crm-tabs">{["OPEN", "IN_PROGRESS", "COMPLETED", "ALL"].map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item.replaceAll("_", " ")}</button>)}</section><section className="crm-task-list">{visible.map((task) => <article key={task.id} className={task.status === "COMPLETED" ? "crm-task-complete" : ""}><button className="crm-task-check" onClick={() => void mutate({ action: "toggle_task", taskId: task.id }, task.status === "COMPLETED" ? "Task reopened" : "Task completed")} aria-label={task.status === "COMPLETED" ? `Reopen ${task.title}` : `Complete ${task.title}`}>{task.status === "COMPLETED" ? "✓" : ""}</button><div><strong>{task.title}</strong><p>{task.description || "No description"}</p><span>{clients.find((client) => client.id === task.clientId)?.businessName} · {task.assignee ?? "Unassigned"}</span></div><div><Badge tone={task.priority === "URGENT" ? "red" : task.priority === "HIGH" ? "orange" : "neutral"}>{task.priority}</Badge><small>{dateTime(task.dueAt)}</small></div></article>)}{!visible.length ? <EmptyState title="No tasks in this view" description="Create a task when a lead needs a clear next step." /> : null}</section></div>;
}

export function CalendarView({ appointments, mutate, onAddAppointment }: { appointments: CrmAppointment[]; mutate: Mutate; onAddAppointment: () => void }) {
  const [mode, setMode] = useState<"upcoming" | "all">("upcoming");
  const visible = appointments.filter((appointment) => mode === "all" || (!["COMPLETED", "CANCELED"].includes(appointment.status)));
  const grouped = visible.reduce<Record<string, CrmAppointment[]>>((acc, appointment) => {
    const key = appointment.startsAt.slice(0, 10);
    (acc[key] ??= []).push(appointment);
    return acc;
  }, {});
  return <div className="crm-view"><section className="crm-page-heading"><div><p>APPOINTMENTS</p><h2>Calendar</h2><span>Schedule service visits and keep their status current.</span></div><button className="crm-button-primary" onClick={onAddAppointment}>+ Book Appointment</button></section><section className="crm-tabs"><button className={mode === "upcoming" ? "active" : ""} onClick={() => setMode("upcoming")}>Upcoming</button><button className={mode === "all" ? "active" : ""} onClick={() => setMode("all")}>All appointments</button></section><section className="crm-calendar-list">{Object.entries(grouped).map(([day, items]) => <article key={day}><header><strong>{new Date(`${day}T12:00:00`).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}</strong><span>{items.length} appointment{items.length === 1 ? "" : "s"}</span></header>{items.map((appointment) => <div key={appointment.id}><time>{new Date(appointment.startsAt).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}</time><span className="crm-avatar">{appointment.contactName.split(/\s+/).map((part) => part[0]).slice(0, 2).join("")}</span><div><strong>{appointment.contactName}</strong><p>{appointment.serviceType} · {appointment.clientName}</p><small>{appointment.address ?? "Address not provided"}</small></div><select value={appointment.status} onChange={(event) => void mutate({ action: "update_appointment_status", appointmentId: appointment.id, status: event.target.value }, "Appointment status updated")} aria-label={`Status for ${appointment.contactName}`}>{["SCHEDULED", "CONFIRMED", "COMPLETED", "CANCELED", "NO_SHOW"].map((status) => <option key={status}>{status}</option>)}</select></div>)}</article>)}{!visible.length ? <EmptyState title="No appointments yet" description="Book an appointment from a qualified lead or contact." /> : null}</section></div>;
}

export function ClientsView({ clients, leads, onAddClient, mutate }: { clients: CrmClient[]; leads: CrmLead[]; onAddClient: () => void; mutate: Mutate }) {
  async function archive(client: CrmClient) {
    if (!window.confirm(`Archive ${client.businessName}? Its records will be retained but hidden from active agency views.`)) return;
    await mutate({ action: "archive_client", clientId: client.id }, "Client archived");
  }
  return <div className="crm-view"><section className="crm-page-heading"><div><p>CLIENT MANAGEMENT</p><h2>Clients</h2><span>Manage business profiles, budgets, service areas, and account ownership.</span></div><button className="crm-button-primary" onClick={onAddClient}>+ Add Client</button></section><section className="crm-client-grid">{clients.map((client) => { const clientLeads = leads.filter((lead) => lead.clientId === client.id); const revenue = clientLeads.reduce((sum, lead) => sum + lead.finalRevenueCents, 0); return <article key={client.id}><header><span className="crm-client-logo">{client.businessName.split(/\s+/).map((part) => part[0]).slice(0, 2).join("")}</span><div><strong>{client.businessName}</strong><small>{client.industry} · {client.city}, {client.state}</small></div><Badge tone="green">{client.status}</Badge></header><section><div><span>Leads</span><strong>{clientLeads.length}</strong></div><div><span>Revenue</span><strong>{money(revenue)}</strong></div><div><span>Ad budget</span><strong>{money(client.monthlyAdBudgetCents)}</strong></div></section><dl><div><dt>Account manager</dt><dd>{client.assignedAccountManager ?? "Unassigned"}</dd></div><div><dt>Service areas</dt><dd>{client.serviceAreas.join(", ") || "Not set"}</dd></div><div><dt>Website</dt><dd>{client.website ?? "Not connected"}</dd></div></dl><footer><span>Created {shortDate(client.createdAt)}</span><button onClick={() => void archive(client)}>Archive</button></footer></article>; })}</section></div>;
}

export function ReportsView({ leads, clients }: { leads: CrmLead[]; clients: CrmClient[] }) {
  const stages = ["NEW", "CONTACTED", "QUALIFIED", "APPOINTMENT_BOOKED", "ESTIMATE_SENT", "WON"];
  const funnel = stages.map((status) => ({ status, count: leads.filter((lead) => lead.status === status).length }));
  const max = Math.max(1, ...funnel.map((item) => item.count));
  const sourceRows = Object.entries(leads.reduce<Record<string, { leads: number; revenue: number }>>((acc, lead) => { const row = acc[lead.source] ?? { leads: 0, revenue: 0 }; row.leads += 1; row.revenue += lead.finalRevenueCents; acc[lead.source] = row; return acc; }, {})).sort((a, b) => b[1].leads - a[1].leads);
  const spend = clients.reduce((sum, client) => sum + client.monthlyAdBudgetCents, 0);
  const revenue = leads.reduce((sum, lead) => sum + lead.finalRevenueCents, 0);
  return <div className="crm-view crm-report-view"><section className="crm-page-heading"><div><p>PERFORMANCE REPORT</p><h2>Agency report</h2><span>Executive summary for the current client and date filters.</span></div><button className="crm-button-secondary" onClick={() => window.print()}>Print / Save PDF</button></section><div className="crm-report-note"><Badge tone="green">Live workspace</Badge><p>Ad-platform and call data are not connected yet. This report uses only real CRM records currently stored in Brizuela Leads.</p></div><section className="crm-report-summary"><article><span>Leads</span><strong>{leads.length}</strong></article><article><span>Revenue</span><strong>{money(revenue)}</strong></article><article><span>Ad spend</span><strong>{money(spend)}</strong></article><article><span>ROAS</span><strong>{spend ? `${(revenue / spend).toFixed(2)}x` : "0x"}</strong></article></section><section className="crm-dashboard-grid"><article className="crm-panel"><header><div><p>SALES FUNNEL</p><h3>Lead progression</h3></div></header><div className="crm-funnel">{funnel.map((item) => <div key={item.status}><span>{item.status.replaceAll("_", " ")}</span><i><b style={{ width: `${Math.max(5, (item.count / max) * 100)}%` }} /></i><strong>{item.count}</strong></div>)}</div></article><article className="crm-panel"><header><div><p>LEAD SOURCES</p><h3>Volume and revenue</h3></div></header><table className="crm-mini-table"><thead><tr><th>Source</th><th>Leads</th><th>Revenue</th></tr></thead><tbody>{sourceRows.map(([source, row]) => <tr key={source}><td>{source}</td><td>{row.leads}</td><td>{money(row.revenue)}</td></tr>)}</tbody></table></article></section><section className="crm-panel crm-report-recommendations"><header><div><p>RECOMMENDATIONS</p><h3>What to do next</h3></div></header><ol><li><strong>Respond to new leads first.</strong><span>{leads.filter((lead) => lead.status === "NEW").length} leads still need a first response.</span></li><li><strong>Follow up on open estimates.</strong><span>{leads.filter((lead) => lead.status === "ESTIMATE_SENT").length} estimate-stage opportunities can be closed.</span></li><li><strong>Connect live marketing data.</strong><span>Meta Ads, Google Ads, and call tracking remain Phase 2 integrations.</span></li></ol></section></div>;
}

export function TeamView({ team, onInvite }: { team: CrmTeamMember[]; onInvite: () => void }) {
  return <div className="crm-view"><section className="crm-page-heading"><div><p>ACCESS CONTROL</p><h2>Team</h2><span>Agency roles are enforced on the server for every CRM request.</span></div><button className="crm-button-primary" onClick={onInvite}>+ Invite Member</button></section><section className="crm-table-panel"><table className="crm-table"><thead><tr><th>Member</th><th>Role</th><th>Status</th><th>Last sign in</th></tr></thead><tbody>{team.map((member) => <tr key={member.id}><td><span className="crm-table-person"><i>{member.displayName.split(/\s+/).map((part) => part[0]).slice(0, 2).join("")}</i><span><strong>{member.displayName}</strong><small>{member.email}</small></span></span></td><td>{member.role.replaceAll("_", " ")}</td><td><Badge tone={member.status === "active" ? "green" : "red"}>{member.status}</Badge></td><td>{member.lastLoginAt ? dateTime(member.lastLoginAt) : "Invite pending"}</td></tr>)}</tbody></table></section></div>;
}

export function SettingsView({ organizationName, viewerRole, clients }: { organizationName: string; viewerRole: string; clients: CrmClient[] }) {
  return <div className="crm-view"><section className="crm-page-heading"><div><p>WORKSPACE SETTINGS</p><h2>Settings</h2><span>Production safeguards and configuration readiness for {organizationName}.</span></div></section><section className="crm-settings-grid"><article><h3>Organization</h3><dl><div><dt>Name</dt><dd>{organizationName}</dd></div><div><dt>Your role</dt><dd>{viewerRole.replaceAll("_", " ")}</dd></div><div><dt>Active clients</dt><dd>{clients.length}</dd></div></dl></article><article><h3>Security</h3><ul><li><span>✓</span><div><strong>ChatGPT authentication</strong><p>Hosted passwords and sessions are handled outside Brizuela Leads.</p></div></li><li><span>✓</span><div><strong>Server-side tenant isolation</strong><p>Every read and write is scoped to an authorized organization and client.</p></div></li><li><span>✓</span><div><strong>Audit logging</strong><p>Lead, task, client, appointment, and membership changes are recorded.</p></div></li></ul></article><article><h3>Integrations</h3><div className="crm-unavailable-list"><span><strong>Twilio / CallRail</strong><Badge tone="neutral">Phase 2</Badge></span><span><strong>Meta Ads</strong><Badge tone="neutral">Phase 2</Badge></span><span><strong>Google Ads</strong><Badge tone="neutral">Phase 2</Badge></span><span><strong>OpenAI</strong><Badge tone="neutral">Phase 3</Badge></span><span><strong>Stripe</strong><Badge tone="neutral">Phase 4</Badge></span></div></article><article><h3>Privacy controls</h3><ul><li><span>✓</span><div><strong>Consent status</strong><p>Stored separately for every contact and lead.</p></div></li><li><span>✓</span><div><strong>Soft deletion</strong><p>Archived records remain available for audit and recovery.</p></div></li><li><span>—</span><div><strong>Automated retention</strong><p>Configuration is planned for Phase 3.</p></div></li></ul></article></section></div>;
}
